services:
  sampleprojectbackend.api:
    image: ${DOCKER_REGISTRY-}sampleprojectbackendapi
    container_name: sampleprojectbackend_api
    build:
      context: .
      dockerfile: SampleProjectBackEnd.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnectionMYSQL=Server=db;Port=3306;Database=sampledb;Uid=appuser;Pwd=1355;
    depends_on:
      - db
    networks:
      - sampleproject_network

  db:
    image: mysql:latest
    container_name: sampleprojectbackend_db
    environment:
      MYSQL_ROOT_PASSWORD: 1355
      MYSQL_DATABASE: sampledb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: 1355
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sampleproject_network

volumes:
  mysql_data:


networks:
  sampleproject_network:
    driver: bridge
